import type { Condition, Modifier, StatKey } from "./types";

const pen = (stats: StatKey[], value: number): Modifier[] =>
  stats.map((stat) => ({ stat, value, type: "untyped" }));

/** Condições do SRD 3.5 como efeitos prontos. Parte situacional fica no resumo. */
export const CONDITIONS: Condition[] = [
  {
    key: "blinded",
    name: "Blinded",
    namePt: "Cego",
    summaryPt:
      "−2 na CA, perde Des na CA, metade do deslocamento, −4 em perícias de For/Des; 50% de falha contra alvos (camuflagem total).",
    modifiers: pen(["ac"], -2),
    flags: ["loseDexToAc", "halfSpeed"],
  },
  {
    key: "cowering",
    name: "Cowering",
    namePt: "Encolhido",
    summaryPt: "Paralisado de medo: sem ações, −2 na CA, perde Des na CA.",
    modifiers: pen(["ac"], -2),
    flags: ["loseDexToAc", "noActions"],
  },
  {
    key: "dazed",
    name: "Dazed",
    namePt: "Pasmo",
    summaryPt: "Sem ações (normalmente 1 rodada), sem penalidade na CA.",
    modifiers: [],
    flags: ["noActions"],
  },
  {
    key: "dazzled",
    name: "Dazzled",
    namePt: "Ofuscado",
    summaryPt: "−1 nos ataques e em Procurar e Observar.",
    modifiers: pen(["attack", "skill.search", "skill.spot"], -1),
    flags: [],
  },
  {
    key: "deafened",
    name: "Deafened",
    namePt: "Surdo",
    summaryPt: "−4 na iniciativa, falha em Ouvir, 20% de falha em magias com componente verbal.",
    modifiers: pen(["init"], -4),
    flags: [],
  },
  {
    key: "disabled",
    name: "Disabled",
    namePt: "Incapacitado",
    summaryPt:
      "Com 0 PV: só uma ação padrão ou de movimento por rodada; ação extenuante causa 1 de dano.",
    modifiers: [],
    flags: ["singleAction"],
  },
  {
    key: "entangled",
    name: "Entangled",
    namePt: "Enredado",
    summaryPt:
      "−2 nos ataques, −4 de Des, metade do deslocamento, não corre nem investe; concentração para conjurar.",
    modifiers: [...pen(["attack"], -2), ...pen(["dex"], -4)],
    flags: ["halfSpeed", "noRun"],
  },
  {
    key: "exhausted",
    name: "Exhausted",
    namePt: "Exausto",
    summaryPt: "−6 de For e Des, metade do deslocamento. 1 hora de descanso vira fatigado.",
    modifiers: pen(["str", "dex"], -6),
    flags: ["halfSpeed", "noRun"],
  },
  {
    key: "fatigued",
    name: "Fatigued",
    namePt: "Fatigado",
    summaryPt: "−2 de For e Des, não corre nem investe.",
    modifiers: pen(["str", "dex"], -2),
    flags: ["noRun"],
  },
  {
    key: "flat-footed",
    name: "Flat-Footed",
    namePt: "Desprevenido",
    summaryPt: "Antes de agir no combate: perde Des na CA, não faz ataques de oportunidade.",
    modifiers: [],
    flags: ["loseDexToAc"],
  },
  {
    key: "frightened",
    name: "Frightened",
    namePt: "Amedrontado",
    summaryPt: "Foge da fonte do medo; −2 em ataques, resistências, perícias e testes de atributo.",
    modifiers: pen(["attack", "save.all", "skill.all"], -2),
    flags: [],
  },
  {
    key: "grappling",
    name: "Grappling",
    namePt: "Agarrando",
    summaryPt:
      "Não se move livremente, não ameaça; perde Des na CA contra quem não está na luta. Só certas ações.",
    modifiers: [],
    flags: ["noMove"],
  },
  {
    key: "helpless",
    name: "Helpless",
    namePt: "Indefeso",
    summaryPt: "Des efetiva 0 (−5 na CA); corpo a corpo tem +4; pode sofrer golpe de misericórdia.",
    modifiers: [],
    flags: ["helpless", "loseDexToAc", "noActions", "noMove"],
  },
  {
    key: "nauseated",
    name: "Nauseated",
    namePt: "Nauseado",
    summaryPt: "Só uma ação de movimento por rodada; não ataca, conjura nem se concentra.",
    modifiers: [],
    flags: ["singleAction"],
  },
  {
    key: "panicked",
    name: "Panicked",
    namePt: "Em pânico",
    summaryPt: "Larga o que segura e foge; −2 em resistências, perícias e testes de atributo.",
    modifiers: pen(["save.all", "skill.all"], -2),
    flags: [],
  },
  {
    key: "paralyzed",
    name: "Paralyzed",
    namePt: "Paralisado",
    summaryPt: "For e Des efetivas 0, indefeso; só ações puramente mentais.",
    modifiers: [],
    flags: ["helpless", "loseDexToAc", "noActions", "noMove"],
  },
  {
    key: "pinned",
    name: "Pinned",
    namePt: "Imobilizado",
    summaryPt:
      "Preso na luta corporal: não se move, perde Des na CA; −4 na CA contra outros atacantes.",
    modifiers: [],
    flags: ["loseDexToAc", "noMove"],
  },
  {
    key: "prone",
    name: "Prone",
    namePt: "Caído",
    summaryPt:
      "−4 em ataques corpo a corpo, não usa arma de distância (exceto besta); +4 na CA contra distância, −4 contra corpo a corpo.",
    modifiers: pen(["attack.melee"], -4),
    flags: [],
  },
  {
    key: "shaken",
    name: "Shaken",
    namePt: "Abalado",
    summaryPt: "−2 em ataques, resistências, perícias e testes de atributo.",
    modifiers: pen(["attack", "save.all", "skill.all"], -2),
    flags: [],
  },
  {
    key: "sickened",
    name: "Sickened",
    namePt: "Enjoado",
    summaryPt: "−2 em ataques, dano com armas, resistências, perícias e testes de atributo.",
    modifiers: pen(["attack", "damage", "save.all", "skill.all"], -2),
    flags: [],
  },
  {
    key: "staggered",
    name: "Staggered",
    namePt: "Cambaleante",
    summaryPt: "Só uma ação padrão ou de movimento por rodada.",
    modifiers: [],
    flags: ["singleAction"],
  },
  {
    key: "stunned",
    name: "Stunned",
    namePt: "Atordoado",
    summaryPt: "Larga o que segura, sem ações, −2 na CA, perde Des na CA.",
    modifiers: pen(["ac"], -2),
    flags: ["loseDexToAc", "noActions"],
  },
  {
    key: "unconscious",
    name: "Unconscious",
    namePt: "Inconsciente",
    summaryPt: "Desacordado e indefeso.",
    modifiers: [],
    flags: ["helpless", "loseDexToAc", "noActions", "noMove"],
  },
];
