import type { Race } from "./types";

/** As 7 raças do Livro do Jogador (SRD 3.5). Bônus condicionais ficam só no texto. */
export const RACES: Race[] = [
  {
    id: "human",
    name: "Human",
    namePt: "Humano",
    size: "medium",
    speed: 30,
    abilityAdjustments: {},
    modifiers: [],
    bonusFeats: 1,
    bonusSkillPoints: { first: 4, perLevel: 1 },
    favoredClass: "any",
    languages: ["Common"],
    bonusLanguages: ["any"],
    traitsPt: [
      "1 talento extra no 1º nível.",
      "4 pontos de perícia extras no 1º nível e 1 a cada nível seguinte.",
      "Classe favorecida: qualquer uma.",
    ],
  },
  {
    id: "dwarf",
    name: "Dwarf",
    namePt: "Anão",
    size: "medium",
    speed: 20,
    abilityAdjustments: { con: 2, cha: -2 },
    speedIgnoresLoad: true,
    modifiers: [],
    bonusFeats: 0,
    bonusSkillPoints: { first: 0, perLevel: 0 },
    favoredClass: "fighter",
    languages: ["Common", "Dwarven"],
    bonusLanguages: ["Giant", "Gnome", "Goblin", "Orc", "Terran", "Undercommon"],
    traitsPt: [
      "Deslocamento 6 m, mesmo com armadura média/pesada ou carga média/pesada.",
      "Visão no escuro 18 m; ligação com pedras (+2 Procurar em trabalhos em pedra).",
      "Estabilidade: +4 contra encontrão e imobilização.",
      "+2 nos testes de resistência contra venenos, magias e efeitos similares.",
      "+1 de ataque contra orcs e goblinoides; +4 de esquiva na CA contra gigantes.",
      "+2 em Avaliação e Ofício ligados a pedra ou metal.",
      "Classe favorecida: guerreiro.",
    ],
  },
  {
    id: "elf",
    name: "Elf",
    namePt: "Elfo",
    size: "medium",
    speed: 30,
    abilityAdjustments: { dex: 2, con: -2 },
    modifiers: [
      { stat: "skill.listen", value: 2, type: "racial" },
      { stat: "skill.search", value: 2, type: "racial" },
      { stat: "skill.spot", value: 2, type: "racial" },
    ],
    bonusFeats: 0,
    bonusSkillPoints: { first: 0, perLevel: 0 },
    favoredClass: "wizard",
    languages: ["Common", "Elven"],
    bonusLanguages: ["Draconic", "Gnoll", "Gnome", "Goblin", "Orc", "Sylvan"],
    traitsPt: [
      "Imune a efeitos mágicos de sono; +2 contra encantamentos.",
      "Visão na penumbra.",
      "Usar Armas (espada longa, sabre, arcos longo e curto, inclusive compostos).",
      "+2 em Ouvir, Procurar e Observar; nota portas secretas ao passar perto.",
      "Classe favorecida: mago.",
    ],
  },
  {
    id: "gnome",
    name: "Gnome",
    namePt: "Gnomo",
    size: "small",
    speed: 20,
    abilityAdjustments: { con: 2, str: -2 },
    modifiers: [
      { stat: "skill.listen", value: 2, type: "racial" },
      { stat: "skill.craft.alchemy", value: 2, type: "racial" },
    ],
    bonusFeats: 0,
    bonusSkillPoints: { first: 0, perLevel: 0 },
    favoredClass: "bard",
    languages: ["Common", "Gnome"],
    bonusLanguages: ["Draconic", "Dwarven", "Elven", "Giant", "Goblin", "Orc"],
    traitsPt: [
      "Pequeno: +1 na CA e no ataque, +4 em Esconder-se, −4 em agarrar.",
      "Visão na penumbra.",
      "+2 contra ilusões; +1 na CD das ilusões que conjura.",
      "+1 de ataque contra kobolds e goblinoides; +4 de esquiva na CA contra gigantes.",
      "Magias inatas: falar com animais (1/dia); com Car 10+, globos de luz, som fantasma e prestidigitação.",
      "Classe favorecida: bardo.",
    ],
  },
  {
    id: "half-elf",
    name: "Half-Elf",
    namePt: "Meio-elfo",
    size: "medium",
    speed: 30,
    abilityAdjustments: {},
    modifiers: [
      { stat: "skill.listen", value: 1, type: "racial" },
      { stat: "skill.search", value: 1, type: "racial" },
      { stat: "skill.spot", value: 1, type: "racial" },
      { stat: "skill.diplomacy", value: 2, type: "racial" },
      { stat: "skill.gather-information", value: 2, type: "racial" },
    ],
    bonusFeats: 0,
    bonusSkillPoints: { first: 0, perLevel: 0 },
    favoredClass: "any",
    languages: ["Common", "Elven"],
    bonusLanguages: ["any"],
    traitsPt: [
      "Imune a efeitos mágicos de sono; +2 contra encantamentos.",
      "Visão na penumbra; sangue élfico.",
      "+1 em Ouvir, Procurar e Observar; +2 em Diplomacia e Obter Informação.",
      "Classe favorecida: qualquer uma.",
    ],
  },
  {
    id: "half-orc",
    name: "Half-Orc",
    namePt: "Meio-orc",
    size: "medium",
    speed: 30,
    abilityAdjustments: { str: 2, int: -2, cha: -2 },
    modifiers: [],
    bonusFeats: 0,
    bonusSkillPoints: { first: 0, perLevel: 0 },
    favoredClass: "barbarian",
    languages: ["Common", "Orc"],
    bonusLanguages: ["Draconic", "Giant", "Gnoll", "Goblin", "Abyssal"],
    traitsPt: ["Visão no escuro 18 m; sangue orc.", "Classe favorecida: bárbaro."],
  },
  {
    id: "halfling",
    name: "Halfling",
    namePt: "Halfling",
    size: "small",
    speed: 20,
    abilityAdjustments: { dex: 2, str: -2 },
    modifiers: [
      { stat: "skill.climb", value: 2, type: "racial" },
      { stat: "skill.jump", value: 2, type: "racial" },
      { stat: "skill.move-silently", value: 2, type: "racial" },
      { stat: "skill.listen", value: 2, type: "racial" },
      { stat: "save.all", value: 1, type: "racial" },
    ],
    bonusFeats: 0,
    bonusSkillPoints: { first: 0, perLevel: 0 },
    favoredClass: "rogue",
    languages: ["Common", "Halfling"],
    bonusLanguages: ["Dwarven", "Elven", "Gnome", "Goblin", "Orc"],
    traitsPt: [
      "Pequeno: +1 na CA e no ataque, +4 em Esconder-se, −4 em agarrar.",
      "+2 em Escalar, Saltar, Furtividade e Ouvir.",
      "+1 em todos os testes de resistência; +2 de moral contra medo.",
      "+1 de ataque com armas de arremesso e fundas.",
      "Classe favorecida: ladino.",
    ],
  },
];
